add new state if we are unable to charge members
HedvigInsurance/account-service pull request #111
Opened 2020-11-03 13:06 UTC by AlexSJ1990

2020-11-04 07:57 UTC, FredrikAreschoug reviewed
Looks good! But should we add a reason and the exception from why we were unable to charge? I would like it when debugging :slightly_smiling_face:

2020-11-04 08:05 UTC, johantjellden commented
> Looks good! But should we add a reason and the exception from why we were unable to charge? I would like it when debugging 🙂

Yes and lets not consider this done until we have code in place that dispatches the new command.

2020-11-04 15:34 UTC, vonElfvin requested changes
Great job, clean solution. Missing @EventListener however for the database

2020-11-04 15:34 UTC, vonElfvin commented on src/main/kotlin/com/hedvig/accountservice/schedulers/domain/MemberScheduler.kt
> +    }
Let's make sure this is reflected in the database

2020-11-04 15:34 UTC, vonElfvin commented on src/main/kotlin/com/hedvig/accountservice/schedulers/domain/MemberScheduler.kt
> +        ),
Should we add "CHARGE_REQUESTING" here, i.e. that you can try again without going through the whole loop

2020-11-04 15:34 UTC, vonElfvin commented on src/main/kotlin/com/hedvig/accountservice/schedulers/model/ChargeStatus.kt
> +    UNABLE_TO_INITIATE_CHARGE,
```suggestion
    UNABLE_TO_REQUEST_CHARGE,
```

2020-11-04 15:34 UTC, vonElfvin commented on src/main/kotlin/com/hedvig/accountservice/schedulers/model/ChargeStatus.kt
> +    UNABLE_TO_INITIATE_CHARGE,
Maybe
```suggestion
    CHARGE_REQUEST_ERROR,
```

2020-11-04 16:24 UTC, AlexSJ1990 commented on src/main/kotlin/com/hedvig/accountservice/schedulers/domain/MemberScheduler.kt
> +        ),
yess very good idea, I was wondering if this was okay to do!

2020-11-05 08:13 UTC, vonElfvin commented on src/test/kotlin/com/hedvig/accountservice/schedulers/domain/MemberSchedulerTest.kt
> +    @Test
Should probably add a test to the `ChargeSaga` as well so we know it sends this command when it gets and exception in the product-pricing client

2020-11-05 08:17 UTC, vonElfvin commented on src/main/kotlin/com/hedvig/accountservice/schedulers/domain/commands/UnableToRequestChargeCommand.kt
> +)
If you want to log it
```suggestion
data class UnableToRequestChargeCommand(
    @TargetAggregateIdentifier
    val memberId: String,
    val amount: MonetaryAmount,
    val scheduledBy: String,
    val exception: Exception
)
```

2020-11-05 11:55 UTC, vonElfvin commented on src/main/kotlin/com/hedvig/accountservice/schedulers/domain/MemberScheduler.kt
> +        logger.error { "Unable to request charge for memberId=${command.memberId}, exception: ${command.exception}" }
Aparently you can do
```suggestion
        logger.error (command.exception) { "Unable to request charge for memberId=${command.memberId}" }
```

2020-11-06 08:23 UTC, FredrikAreschoug approved these changes

2020-11-06 13:09 UTC, vonElfvin approved these changes

2020-11-06 13:09 UTC, merged